# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  password:
    secure: rt83XuW2Dp8ClebsiVRXLEL0FTS2pJf5POM3R+4S6OCT8nFcb30Ipc0WFMFipNn+tpPPMpSmrscC/on6CBR244BoZyL4Ipbkosz1u9IHOfPSubrii7JlJ7bFrVvg/wYqtYuodED5EIWlrtPNWcfMnMfjOHzlBX/lrjQa6ZLXyNP1HaiBsmCsom/br/SxifHuPWy+KIQZCvv97sFZlzmLk+8mhOUm2y18FDFgQJ4o9qXehuJlrmCoI84RChrHIFG/9G97PmJS0g52B0nidI6YHaBmTsyUvkHSxB4S3xEyFA+chtpWFvu8kXjQA8pCmWYxaqrY6BVHKWt95Deu4DKyd2yRgGIb0oN0VmvRELT45/5MdVXhixu/TLRkUJxoSN0u7G4D2AmGU4TxWswCL+o1mgnulzCYfwaw4wwyEbdZNfwoC6mAM7N+UtDNNfnJepItL6UXgNZk5ZrDNofYeXe452mnHH1Mi3nTi+s3H17f9iopiX1WZZfw5MVBF+c/Wk6btF+dvav1GMjIAIeeycfFOgFWq8roRYF7OnjA1cx0w2j/t6hraj1TO4Xyfj3IObZ+I29jw6c9KAhTQPoHOSWj6DSL5l66XlH+KWArWmZvATiEtwSIzx1pK8+dM9YbmxCj/eQUmwhot1iVGXVrIyCATr48u7E9RcBbj4E2NnNBRgc=
  on:
    tags: true
install:
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
script:
- pylint adafruit_bus_device/*.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-bus-device
  --library_location .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
