/*
 * The Wakey module was written to fill a need for a way to put the Itsy Bitsy
 * M0 Express into standby mode when it's services aren't needed.  Putting the
 * SamD21 in Standby mode lets us get a lot more out of our battery when we put
 * devices in places (e.g.: outdoors) where we need to recharge the power supplies.
 *
 */
#include "py/obj.h"
#include "py/runtime.h"
// for gpio and pin functions
//
// atmel_start_pins.h is auto generated by atmel start.  From what I can tell,
// there is a cool view of the pins in the PINMUX ui of Atmel Start.
// asf4/samd21/atmel_start_pins.h
// for example:
// #define PA02 GPIO(GPIO_PORTA, 2)
#include "atmel_start_pins.h"
//
// hal_gpio.h has the nifty functions for setting GPIO pins (e.g.: toggle, set, get..)
// asf4/samd21/hal/include/hal_gpio.h
#include "hal/include/hal_gpio.h"
//
// DigitalInOut.h has the goop to work with the pin functions / structures
// in the CP DigitalInOut module.
#include "shared-bindings/digitalio/DigitalInOut.h"
//
// Pin.h exposes the CP microcontroller object.  It includes
// ports/atmel-samd/common-hall/digitalio/DigitalInOut.h which has stuff like
// extern const mp_obj_type_t mcu_pin_type; and
// void assert_pin(mp_obj_t obj, bool none_ok);
#include "shared-bindings/microcontroller/Pin.h"
//
// pins.h has defines such as:
// #ifdef PIN_PA03
// extern const mcu_pin_obj_t pin_PA03;
// #endif
#include "samd/pins.h"
//
// The EIC Handlers are defined in external_interrupts.h
//
#include "samd/external_interrupts.h"
// Put helper functions in this lib...
#include "wakey_helpers.h"
// Give a name to the LED pin on the itsy bitsy.
// The CP pin mappings to SamD pin mappings are defined in
// ports/atmel-samd/itsybitsy_m0_express/pins.c
// D13 is for the red LED:
// { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_PA17) },
// which...ultimately...devolves into ... pin 17?
#define LED0 GPIO(GPIO_PORTA, 17)



//#pragma GCC push_options
//#pragma GCC optimize ("O0")

//*********************************************************************
// zzz(CP pin) - pin is a circuit python GPIO pin that will change level
// to wake from standby mode.
//*********************************************************************
STATIC mp_obj_t  zzz(mp_obj_t pin_in) {
  assert_pin(pin_in,false);
  init_LED();
  // Map from CP pin structure to SamD21 pin structure.
  mcu_pin_obj_t *pin = MP_OBJ_TO_PTR(pin_in);
  digitalio_digitalinout_obj_t int_pin;
  common_hal_digitalio_digitalinout_construct(&int_pin, pin);
  //
  config_GPIO(int_pin.pin->pin);
  config_EIC(int_pin.pin->extint_channel);
	//register_callback(int_pin.pin->extint_channel, EIC_HANDLER_LOWPOWER);
	time_to_sleep();
  wakey_interrupt_handler(3) ;
  return mp_const_none;
}
// zzz() takes in the (CircuitPython) pin
// that will be configured to wake up the mo from standby
// mode when...
STATIC MP_DEFINE_CONST_FUN_OBJ_1(zzz_obj, zzz);

/*
* Wakey module
*/
// Dictionary of globals
STATIC const mp_map_elem_t wakey_module_globals_table[] = {
    { MP_OBJ_NEW_QSTR(MP_QSTR___name__), MP_OBJ_NEW_QSTR(MP_QSTR_Wakey) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_zzz), (mp_obj_t)&zzz_obj },
};
STATIC MP_DEFINE_CONST_DICT(wakey_module_globals, wakey_module_globals_table);
// Define the module
const mp_obj_module_t lowpower_module = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&wakey_module_globals,
};
//#pragma GCC pop_options
